/** Auto-generated by scripts/generate-lab-test-stats.mjs — do not edit manually */
export interface LabTestStats {
  generatedAt: string;
  unitTests: number;
  unitTestFiles: number;
  e2eTests: number;
  e2eSpecFiles: number;
  e2eSmokeTests: number;
  e2eRegressionTests: number;
  totalTests: number;
}

export const labTestStats: LabTestStats = {
  "generatedAt": "2026-07-02T12:29:39.813Z",
  "unitTests": 103,
  "unitTestFiles": 28,
  "e2eTests": 330,
  "e2eSpecFiles": 21,
  "e2eSmokeTests": 22,
  "e2eRegressionTests": 308,
  "totalTests": 433
};
