/** Auto-generated by scripts/generate-lab-test-stats.mjs — do not edit manually */
export interface LabTestStats {
  generatedAt: string;
  unitTests: number;
  unitTestFiles: number;
  e2eTests: number;
  e2eSpecFiles: number;
  e2eSmokeTests: number;
  e2eRegressionTests: number;
  totalTests: number;
}

export const labTestStats: LabTestStats = {
  "generatedAt": "2026-07-02T13:47:39.122Z",
  "unitTests": 115,
  "unitTestFiles": 31,
  "e2eTests": 336,
  "e2eSpecFiles": 21,
  "e2eSmokeTests": 23,
  "e2eRegressionTests": 313,
  "totalTests": 451
};
